# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  -   id: flake8
      additional_dependencies:
        - flake8-isort
      args: ["--max-line-length=88", "--ignore=E266,W503"]

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      language_version: python3.10

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1
  hooks:
    - id: mypy
      args:
       - "--ignore-missing-imports"
       - "--show-column-numbers"
       - "--allow-untyped-defs"
       - "--allow-redefinition"
