# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  -   id: flake8
      additional_dependencies:
        - flake8-isort
      args: ["--max-line-length=88", "--ignore=E203,E266,W503,I001,I005"]

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      language_version: python3.10
